######################################################################
#
# File name : tb_riscv_top_wave.do
# Created on: Tue Jun 20 10:11:09 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
