######################################################################
#
# File name : tb_riscv_top_compile.do
# Created on: Tue Jun 27 18:03:33 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../../rtl/top/EX_UNIT.v" \
"../../../../../rtl/top/ID_UNIT.v" \
"../../../../../rtl/top/IF_UNIT.v" \
"../../../../../rtl/top/RF_UNIT.v" \
"../../../../../rtl/top/RISCV.v" \
"../../../../../rtl/top/RISCV_SOC_TOP.v" \
"../../../../../rtl/core/alu.v" \
"../../../../../rtl/core/cu.v" \
"../../../../../rtl/utils/delay_buffer.v" \
"../../../../../rtl/core/id.v" \
"../../../../../rtl/core/id_ex.v" \
"../../../../../rtl/core/if_id.v" \
"../../../../../rtl/core/pc.v" \
"../../../../../rtl/perips/ram.v" \
"../../../../../rtl/perips/rom.v" \
"../../../../../rtl/perips/uart.v" \
"../../../../../sim/tb_riscv_top.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

