# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010iclg225-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Users/Desktop/FPGA/tinyriscv_cpu/cpu_prj/vivado_prj/cpu_prj.cache/wt [current_project]
set_property parent.project_path D:/Users/Desktop/FPGA/tinyriscv_cpu/cpu_prj/vivado_prj/cpu_prj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Users/Desktop/FPGA/tinyriscv_cpu/cpu_learning_prj/vivado_prj/cpu_prj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/Users/Desktop/FPGA/tinyriscv_cpu/cpu_prj/rtl/core/defines.v
  D:/Users/Desktop/FPGA/tinyriscv_cpu/cpu_prj/rtl/top/EX_UNIT.v
  D:/Users/Desktop/FPGA/tinyriscv_cpu/cpu_prj/rtl/top/ID_UNIT.v
  D:/Users/Desktop/FPGA/tinyriscv_cpu/cpu_prj/rtl/top/IF_UNIT.v
  D:/Users/Desktop/FPGA/tinyriscv_cpu/cpu_prj/rtl/top/RF_UNIT.v
  D:/Users/Desktop/FPGA/tinyriscv_cpu/cpu_prj/rtl/core/alu.v
  D:/Users/Desktop/FPGA/tinyriscv_cpu/cpu_prj/rtl/core/cu.v
  D:/Users/Desktop/FPGA/tinyriscv_cpu/cpu_prj/rtl/core/id.v
  D:/Users/Desktop/FPGA/tinyriscv_cpu/cpu_prj/rtl/core/id_ex.v
  D:/Users/Desktop/FPGA/tinyriscv_cpu/cpu_prj/rtl/core/if_id.v
  D:/Users/Desktop/FPGA/tinyriscv_cpu/cpu_prj/rtl/core/pc.v
  D:/Users/Desktop/FPGA/tinyriscv_cpu/cpu_prj/rtl/perips/ram.v
  D:/Users/Desktop/FPGA/tinyriscv_cpu/cpu_prj/rtl/perips/rom.v
  D:/Users/Desktop/FPGA/tinyriscv_cpu/cpu_prj/rtl/top/RISCV_TOP.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top RISCV_TOP -part xc7z010iclg225-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RISCV_TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RISCV_TOP_utilization_synth.rpt -pb RISCV_TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
